services:
  project:
    build:
      dockerfile: Dockerfile
    command: python ./main.py
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db-service
  db-service:
    image: postgres:12
    environment:
      POSTGRES_DB: rest_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
